In [24]:
import pandas as pd, numpy as np
from math import isnan

In [26]:
tar = "binom"

ess = pd.read_csv("table/ess- "+tar+" .csv")
ess["mse"] = ess.x1 + ess.x2
ess = ess.sort_values("mse")

esssec = pd.read_csv("table/esssec- "+tar+" .csv")
esssec["mse"] = esssec.x1 + esssec.x2
esssec = esssec.sort_values("mse")

for (i1, row), (i2, row2) in zip(ess.iterrows(), esssec.iterrows()):
    print(f"{row.alg}{'(T)' if row.tune else ''} & ${round(row.x1) if not isnan(row.x1) else '-'} \\pm {round(row['x1.1']) if not isnan(row['x1.1']) else '-'}$ & ${round(row.x2) if not isnan(row.x2) else '-'} \\pm {round(row['x2.1']) if not isnan(row['x2.1']) else '-'}$\\\\")
    
print(20 * "--")
    
for (i1, row), (i2, row2) in zip(ess.iterrows(), esssec.iterrows()):
    print(f"{row2.alg}{'(T)' if row2.tune else ''} & ${round(row2.x1) if not isnan(row2.x1) else '-'} \\pm {round(row2['x1.1']) if not isnan(row2.x1) else '-'}$ & ${round(row2.x2) if not isnan(row2.x1) else '-'} \\pm {round(row2['x2.1']) if not isnan(row2.x1) else '-'}$\\\\")

print(20 * "--")
    
for (i1, row), (i2, row2) in zip(ess.iterrows(), esssec.iterrows()):
    print(f"{row.alg}{'(T)' if row.tune else ''} & ${round(row.x1) if not isnan(row.x1) else '-'} \\pm {round(row['x1.1']) if not isnan(row['x1.1']) else '-'}$ & ${round(row.x2) if not isnan(row.x2) else '-'} \\pm {round(row['x2.1']) if not isnan(row['x2.1']) else '-'}$ & ${round(row2.x1) if not isnan(row2.x1) else '-'} \\pm {round(row2['x1.1']) if not isnan(row2['x1.1']) else '-'}$ & ${round(row2.x2) if not isnan(row2.x2) else '-'} \\pm {round(row2['x2.1']) if not isnan(row2['x2.1']) else '-'}$\\\\")

MHS & $8 \pm 3$ & $9 \pm 3$\\
MHS(T) & $13 \pm 5$ & $84 \pm 115$\\
HMC(T) & $432 \pm 385$ & $566 \pm 419$\\
HMC & $645 \pm 346$ & $664 \pm 220$\\
----------------------------------------
MHS & $0 \pm 0$ & $0 \pm 0$\\
MHS(T) & $0 \pm 0$ & $3 \pm 4$\\
HMC(T) & $15 \pm 13$ & $20 \pm 15$\\
HMC & $23 \pm 13$ & $24 \pm 9$\\
----------------------------------------
MHS & $8 \pm 3$ & $9 \pm 3$ & $0 \pm 0$ & $0 \pm 0$\\
MHS(T) & $13 \pm 5$ & $84 \pm 115$ & $0 \pm 0$ & $3 \pm 4$\\
HMC(T) & $432 \pm 385$ & $566 \pm 419$ & $15 \pm 13$ & $20 \pm 15$\\
HMC & $645 \pm 346$ & $664 \pm 220$ & $23 \pm 13$ & $24 \pm 9$\\

In [56]:
tar = "binom_full"

ess = pd.read_csv("table/ess- "+tar+" .csv")
ess["mse"] = ess.x1 + ess.x2
ess = ess.sort_values("mse")

esssec = pd.read_csv("table/esssec- "+tar+" .csv")
esssec["mse"] = esssec.x1 + esssec.x2
esssec = esssec.sort_values("mse")

for (i1, row), (i2, row2) in zip(ess.iterrows(), esssec.iterrows()):
    print(f"{row.alg}{'(T)' if row.tune else ''} & ${round(row.x1) if not isnan(row.x1) else '-'} \\pm {round(row['x1.1']) if not isnan(row['x1.1']) else '-'}$ & ${round(row.x2) if not isnan(row.x2) else '-'} \\pm {round(row['x2.1']) if not isnan(row['x2.1']) else '-'}$\\\\")
    
print(20 * "--")
    
for (i1, row), (i2, row2) in zip(ess.iterrows(), esssec.iterrows()):
    print(f"{row2.alg}{'(T)' if row2.tune else ''} & ${round(row2.x1) if not isnan(row2.x1) else '-'} \\pm {round(row2['x1.1']) if not isnan(row2.x1) else '-'}$ & ${round(row2.x2) if not isnan(row2.x1) else '-'} \\pm {round(row2['x2.1']) if not isnan(row2.x1) else '-'}$\\\\")

print(20 * "--")
    
for (i1, row), (i2, row2) in zip(ess.iterrows(), esssec.iterrows()):
    print(f"{row.alg}{'(T)' if row.tune else ''} & ${round(row.x1) if not isnan(row.x1) else '-'} \\pm {round(row['x1.1']) if not isnan(row['x1.1']) else '-'}$ & ${round(row.x2) if not isnan(row.x2) else '-'} \\pm {round(row['x2.1']) if not isnan(row['x2.1']) else '-'}$ & ${round(row2.x1) if not isnan(row2.x1) else '-'} \\pm {round(row2['x1.1']) if not isnan(row2['x1.1']) else '-'}$ & ${round(row2.x2) if not isnan(row2.x2) else '-'} \\pm {round(row2['x2.1']) if not isnan(row2['x2.1']) else '-'}$\\\\")

ess["x_avg"] = ess[["x" + str(i) for i in range(1, 12)]].mean(axis=1)
ess["x_std"] = ess[["x" + str(i) for i in range(1, 12)]].std(axis=1)
ess["mse"] = ess["x_avg"] - 2 * ess["x_std"]
ess = ess.sort_values("mse")

esssec["x_avg"] = esssec[["x" + str(i) for i in range(1, 12)]].mean(axis=1)
esssec["x_std"] = esssec[["x" + str(i) for i in range(1, 12)]].std(axis=1)
esssec["mse"] = esssec["x_avg"] - 2 * esssec["x_std"]
esssec = esssec.sort_values("mse")

print(20 * "--")

for (i1, row), (i2, row2) in zip(ess.iterrows(), esssec.iterrows()):
    print(f"{row.alg}{'(T)' if row.tune else ''} & ${round(row.x_avg)} \\pm {round(row.x_std)}$ & ${round(row2.x_avg)} \\pm {round(row2.x_std)}$\\\\")

MHS & $8 \pm 3$ & $9 \pm 3$\\
MHS(T) & $13 \pm 5$ & $84 \pm 115$\\
HMC(T) & $432 \pm 385$ & $566 \pm 419$\\
HMC & $645 \pm 346$ & $664 \pm 220$\\
----------------------------------------
MHS & $0 \pm 0$ & $0 \pm 0$\\
MHS(T) & $0 \pm 0$ & $3 \pm 4$\\
HMC(T) & $15 \pm 13$ & $20 \pm 15$\\
HMC & $23 \pm 13$ & $24 \pm 9$\\
----------------------------------------
MHS & $8 \pm 3$ & $9 \pm 3$ & $0 \pm 0$ & $0 \pm 0$\\
MHS(T) & $13 \pm 5$ & $84 \pm 115$ & $0 \pm 0$ & $3 \pm 4$\\
HMC(T) & $432 \pm 385$ & $566 \pm 419$ & $15 \pm 13$ & $20 \pm 15$\\
HMC & $645 \pm 346$ & $664 \pm 220$ & $23 \pm 13$ & $24 \pm 9$\\
----------------------------------------
MHS(T) & $16 \pm 23$ & $1 \pm 1$\\
MHS & $17 \pm 15$ & $1 \pm 1$\\
HMC(T) & $817 \pm 404$ & $29 \pm 14$\\
HMC & $628 \pm 225$ & $22 \pm 8$\\

In [53]:
ess

,Unnamed: 0,alg,tune,x1,x2,x3,x4,x5,x6,x7,...,x5.1,x6.1,x7.1,x8.1,x9.1,x10.1,x11.1,mse,x_avg,x_std
0,4,MHS,True,12.790999,83.694922,8.597022,8.821026,7.653849,6.837857,7.901454,...,1.098680,0.931338,1.235456,20.402873,2.534981,0.795634,3.706032,-28.739866,16.290594,22.515230
1,2,MHS,False,8.302840,9.033531,8.653790,10.979013,14.685576,11.426458,59.104429,...,11.529675,8.849731,110.374196,7.763547,14.379068,8.027032,46.714650,-12.714594,17.336924,15.025759
3,3,HMC,True,432.170571,566.470659,677.711134,661.441555,728.890615,548.040992,577.860665,...,288.082663,219.506988,410.913181,2602.638830,1444.516938,2168.731277,338.425978,8.260796,816.557070,404.148137
2,1,HMC,False,645.316603,663.638647,824.703310,842.811738,189.918915,716.789661,743.396493,...,56.214485,280.608442,265.000540,108.326884,165.477077,112.347930,44.164918,177.868971,628.340288,225.235659

In [54]:
esssec

,Unnamed: 0,alg,tune,x1,x2,x3,x4,x5,x6,x7,...,x5.1,x6.1,x7.1,x8.1,x9.1,x10.1,x11.1,mse,x_avg,x_std
0,4,MHS,True,0.457947,2.868005,0.307463,0.312364,0.269668,0.242385,0.278826,...,0.027283,0.037962,0.036648,0.755179,0.098316,0.034958,0.113176,-0.967751,0.569514,0.768633
1,2,MHS,False,0.296322,0.317346,0.305604,0.385900,0.520707,0.410280,2.157245,...,0.403998,0.330936,4.064187,0.291260,0.535143,0.302714,1.666682,-0.477326,0.622297,0.549811
3,3,HMC,True,14.982566,20.044742,23.578135,23.385530,25.661400,19.292410,20.247305,...,9.874269,7.655470,14.256381,91.007703,50.488610,75.715289,12.089356,0.472085,28.620966,14.074440
2,1,HMC,False,23.159997,23.731597,29.374026,29.631943,6.670574,25.645617,26.247748,...,1.675791,10.632706,9.154191,4.210064,5.015321,4.707851,1.432902,6.305987,22.299788,7.996901